-- MySQL Script generated by MySQL Workbench
-- Sun Feb  6 11:47:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema culdampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema culdampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `culdampolla` DEFAULT CHARACTER SET utf8 ;
USE `culdampolla` ;

-- -----------------------------------------------------
-- Table `culdampolla`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`provider` (
  `id_provider` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `carrer` VARCHAR(45) NULL,
  `numero_carrer` VARCHAR(10) NULL,
  `pis` VARCHAR(45) NULL,
  `porta` VARCHAR(45) NULL,
  `ciutat` VARCHAR(45) NULL,
  `codi_postal` VARCHAR(10) NULL,
  `pais` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `nif` CHAR(8) NULL,
  PRIMARY KEY (`id_provider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`brand` (
  `id_brand` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `id_provider` INT NOT NULL,
  PRIMARY KEY (`id_brand`, `id_provider`),
  INDEX `fk_brand_provider1_idx` (`id_provider` ASC),
  CONSTRAINT `fk_brand_provider1`
    FOREIGN KEY (`id_provider`)
    REFERENCES `culdampolla`.`provider` (`id_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`employee` (
  `id_employee` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id_employee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`customer` (
  `id_customer` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `cognom_1` VARCHAR(45) NULL,
  `cognom_2` VARCHAR(45) NULL,
  `carrer` VARCHAR(45) NULL,
  `numero_carrer` VARCHAR(10) NULL,
  `pis` VARCHAR(45) NULL,
  `porta` VARCHAR(45) NULL,
  `ciutat` VARCHAR(45) NULL,
  `codi_postal` VARCHAR(10) NULL,
  `pais` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `data_registre` DATE NULL,
  `id_recomendador` INT NOT NULL,
  PRIMARY KEY (`id_customer`),
  INDEX `fk_customer_customer1_idx` (`id_recomendador` ASC),
  CONSTRAINT `fk_customer_customer1`
    FOREIGN KEY (`id_recomendador`)
    REFERENCES `culdampolla`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`glasses` (
  `id_glasses` INT NOT NULL,
  `brand` VARCHAR(45) NULL,
  `graduacio_esq` VARCHAR(45) NULL,
  `graduacio_dre` VARCHAR(45) NULL,
  `montura` ENUM('flotant', 'pasta', 'metal') NULL,
  `color_montura` VARCHAR(45) NULL,
  `color_vidre_esq` VARCHAR(45) NULL,
  `color_vidre_dre` VARCHAR(45) NULL,
  `preu` DECIMAL(7,2) NULL,
  `employee` INT NULL,
  `data` DATE NULL,
  `id_employee` INT NOT NULL,
  `id_customer` INT NOT NULL,
  `id_brand` INT NOT NULL,
  PRIMARY KEY (`id_glasses`, `id_employee`, `id_customer`, `id_brand`),
  INDEX `fk_glasses_employee1_idx` (`id_employee` ASC),
  INDEX `fk_glasses_customer1_idx` (`id_customer` ASC),
  INDEX `fk_glasses_brand1_idx` (`id_brand` ASC),
  CONSTRAINT `fk_glasses_employee1`
    FOREIGN KEY (`id_employee`)
    REFERENCES `culdampolla`.`employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_glasses_customer1`
    FOREIGN KEY (`id_customer`)
    REFERENCES `culdampolla`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_glasses_brand1`
    FOREIGN KEY (`id_brand`)
    REFERENCES `culdampolla`.`brand` (`id_brand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
