-- MySQL Script generated by MySQL Workbench
-- Sun Feb 13 13:21:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema culdampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema culdampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `culdampolla` DEFAULT CHARACTER SET utf8 ;
USE `culdampolla` ;

-- -----------------------------------------------------
-- Table `culdampolla`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`provider` (
  `id_provider` INT(11) NOT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `carrer` VARCHAR(45) NULL DEFAULT NULL,
  `numero_carrer` VARCHAR(10) NULL DEFAULT NULL,
  `pis` VARCHAR(45) NULL DEFAULT NULL,
  `porta` VARCHAR(45) NULL DEFAULT NULL,
  `ciutat` VARCHAR(45) NULL DEFAULT NULL,
  `codi_postal` VARCHAR(10) NULL DEFAULT NULL,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  `telefon` VARCHAR(45) NULL DEFAULT NULL,
  `fax` VARCHAR(45) NULL DEFAULT NULL,
  `nif` CHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`id_provider`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `culdampolla`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`brand` (
  `id_brand` INT(11) NOT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `id_provider` INT(11) NOT NULL,
  PRIMARY KEY (`id_brand`, `id_provider`),
  INDEX `fk_brand_provider1_idx` (`id_provider` ASC) ,
  CONSTRAINT `fk_brand_provider1`
    FOREIGN KEY (`id_provider`)
    REFERENCES `culdampolla`.`provider` (`id_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `culdampolla`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`customer` (
  `id_customer` INT(11) NOT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `cognom_1` VARCHAR(45) NULL DEFAULT NULL,
  `cognom_2` VARCHAR(45) NULL DEFAULT NULL,
  `carrer` VARCHAR(45) NULL DEFAULT NULL,
  `numero_carrer` VARCHAR(10) NULL DEFAULT NULL,
  `pis` VARCHAR(45) NULL DEFAULT NULL,
  `porta` VARCHAR(45) NULL DEFAULT NULL,
  `ciutat` VARCHAR(45) NULL DEFAULT NULL,
  `codi_postal` VARCHAR(10) NULL DEFAULT NULL,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  `telefon` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `data_registre` DATE NULL DEFAULT NULL,
  `id_recomendador` INT(11) NOT NULL,
  PRIMARY KEY (`id_customer`),
  INDEX `fk_customer_customer1_idx` (`id_recomendador` ASC) ,
  CONSTRAINT `fk_customer_customer1`
    FOREIGN KEY (`id_recomendador`)
    REFERENCES `culdampolla`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `culdampolla`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`employee` (
  `id_employee` INT(11) NOT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_employee`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `culdampolla`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`modelo` (
  `id_modelo` INT NOT NULL,
  `id_brand` INT(11) NOT NULL,
  `id_provider` INT(11) NOT NULL,
  `montura` ENUM('flotant', 'pasta', 'metal') NULL,
  `precio_modelo` VARCHAR(45) NULL,
  `color_montura` VARCHAR(45) NULL,
  PRIMARY KEY (`id_modelo`, `id_brand`, `id_provider`),
  INDEX `fk_modelo_brand1_idx` (`id_brand` ASC, `id_provider` ASC) ,
  CONSTRAINT `fk_modelo_brand1`
    FOREIGN KEY (`id_brand` , `id_provider`)
    REFERENCES `culdampolla`.`brand` (`id_brand` , `id_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`glasses` (
  `id_glasses` INT(11) NOT NULL,
  `graduacio_esq` VARCHAR(45) NULL DEFAULT NULL,
  `graduacio_dre` VARCHAR(45) NULL DEFAULT NULL,
  `color_vidre_esq` VARCHAR(45) NULL DEFAULT NULL,
  `color_vidre_dre` VARCHAR(45) NULL DEFAULT NULL,
  `preu_vidres` DECIMAL(7,2) NULL DEFAULT NULL,
  `id_modelo` INT NOT NULL,
  `id_brand` INT(11) NOT NULL,
  `id_provider` INT(11) NOT NULL,
  PRIMARY KEY (`id_glasses`, `id_modelo`, `id_brand`, `id_provider`),
  INDEX `fk_glasses_modelo1_idx` (`id_modelo` ASC, `id_brand` ASC, `id_provider` ASC) ,
  CONSTRAINT `fk_glasses_modelo1`
    FOREIGN KEY (`id_modelo` , `id_brand` , `id_provider`)
    REFERENCES `culdampolla`.`modelo` (`id_modelo` , `id_brand` , `id_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `culdampolla`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`sales` (
  `id_sales` INT NOT NULL,
  `data` DATE NULL,
  `id_employee` INT(11) NOT NULL,
  `id_customer` INT(11) NOT NULL,
  `id_glasses` INT(11) NOT NULL,
  PRIMARY KEY (`id_sales`, `id_employee`, `id_customer`, `id_glasses`),
  INDEX `fk_sales_employee1_idx` (`id_employee` ASC) ,
  INDEX `fk_sales_customer1_idx` (`id_customer` ASC) ,
  INDEX `fk_sales_glasses1_idx` (`id_glasses` ASC) ,
  CONSTRAINT `fk_sales_employee1`
    FOREIGN KEY (`id_employee`)
    REFERENCES `culdampolla`.`employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_customer1`
    FOREIGN KEY (`id_customer`)
    REFERENCES `culdampolla`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_glasses1`
    FOREIGN KEY (`id_glasses`)
    REFERENCES `culdampolla`.`glasses` (`id_glasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
